// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Play_by_Play.Areas.Admin.Controllers {
    public partial class ElmahController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ElmahController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ElmahController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ElmahController Actions { get { return MVC.Admin.Elmah; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Elmah";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Stylesheet = "Stylesheet";
            public readonly string Rss = "Rss";
            public readonly string DigestRss = "DigestRss";
            public readonly string About = "About";
            public readonly string Detail = "Detail";
            public readonly string Download = "Download";
            public readonly string Json = "Json";
            public readonly string Xml = "Xml";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ElmahController: Play_by_Play.Areas.Admin.Controllers.ElmahController {
        public T4MVC_ElmahController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Stylesheet() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Stylesheet);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Rss() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Rss);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DigestRss() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DigestRss);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult About() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.About);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Detail() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Detail);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Download() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Download);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Json() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Json);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Xml() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Xml);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
